name: Deploy Next.js to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:${{ github.sha }}

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     script: |
    #       # Pull the latest Docker image
    #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:latest

    #       # Stop existing container if it exists
    #       docker stop nextjs-app || true
    #       docker rm nextjs-app || true

    #       # Run new container
    #       docker run -d \
    #         --name nextjs-app \
    #         -p 3000:3000 \
    #         ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-app:latest
